- platform: cisco_iosxe
  host: 192.168.139.1
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport: paramiko
  transport_options: &transport_alg
    paramiko:
      encryption_algs:
      - aes256-cbc
      - aes192-cbc
      kex_algs:
      - diffie-hellman-group14-sha1
      - diffie-hellman-group1-sha1
- platform: cisco_iosxe
  host: 192.168.139.2
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport_options: *transport_alg
- platform: cisco_iosxe
  host: 192.168.139.3
  auth_username: cisco
  auth_password: cisco
  auth_secondary: cisco
  auth_strict_key: false
  timeout_socket: 5
  timeout_transport: 10
  transport: paramiko
  transport_options: *transport_alg
