version: 1
formatters:
  file_fmt:
    format: "{asctime} {name} {levelname} {message}"
    style: "{"
  stderr_fmt:
    format: "{asctime} {name} {levelname} {message}"
    style: "{"
    datefmt: "%H:%M:%S"
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stderr_fmt
    stream: ext://sys.stderr
  logfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: file_fmt
    filename: "logfile.txt"
loggers:
  "__main__":
    level: DEBUG
    handlers: [stderr, logfile]
    propagate: no
